apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-definition
spec:
  schedule: "0 */1 * * *"
  successfulJobsHistoryLimit: 2
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: all-inference-container
            image: ktaehyun94/all_inference:v1
          restartPolicy: Never
