---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: append-inference-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 4
  selector:
    matchLabels:
      app: append-inference-deploy
  replicas: 4
  template:
    metadata:
      labels:
        app: append-inference-deploy
    spec:
      containers:
        - image: ktaehyun94/append_inference:v3.3
          name: append-inference-deploy
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: append-inference-svc
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  type: NodePort
  selector:
    app: append-inference-deploy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: append-inference-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: ai-alb
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: append-inference-svc
              port:
                number: 80
